[settings]
experimental = true
lockfile = true
github.github_attestations = false
github.slsa = false

[tools]
go = "1.26.3"
golangci-lint = "2.12.2"
goreleaser-pro = "2.16.0"
ko = "0.18.1"

[tool_alias]
goreleaser-pro = "github:goreleaser/goreleaser-pro[exe=goreleaser]"
