image: "buildkite/hosted-agent-base-images:ubuntu-jammy"

agents:
  queue: hosted

cache:
  name: "golang-cache"
  paths:
    - "~/gocache"
    - "~/gomodcache"
  size: "100g"

steps:
  - group: ":mag: Quality Checks"
    key: quality-checks
    steps:
    - name: ":golangci-lint: lint"
      command: golangci-lint run --verbose --timeout 3m
      env:
        - GOCACHE=~/gocache
        - GOMODCACHE=~/gomodcache      
      plugins:
        - mise#v1.1.1: ~

    - name: ":go: test"
      artifact_paths:
        - cover-tree.svg
      commands:
        - go test -coverprofile cover.out ./...
        - go run github.com/nikolaydubina/go-cover-treemap@latest -coverprofile cover.out > cover-tree.svg
        - echo '<details><summary>Coverage tree map</summary><img src="artifact://cover-tree.svg" alt="Test coverage tree map" width="70%"></details>' | buildkite-agent annotate --style "info"
      env:
        - GOCACHE=~/gocache
        - GOMODCACHE=~/gomodcache      
      plugins:
        - mise#v1.1.1: ~

  - label: ":terminal: build ({{matrix}})"
    command: ".buildkite/release.sh release --clean --snapshot --split"
    depends_on: quality-checks
    env:
      - GOCACHE=~/gocache
      - GOMODCACHE=~/gomodcache      
      - GOOS={{matrix}}
    matrix:
      - "darwin"
      - "linux"
      - "windows"
    artifact_paths:
      - dist/**/*
    secrets:
      - MISE_GITHUB_TOKEN
    plugins:
      - mise#v1.1.1: ~

  - label: ":docker: build image"
    depends_on: quality-checks
    command: docker build -t buildkite-mcp-server:latest -f Dockerfile.local .
