image: "buildkite/hosted-agent-base-images:ubuntu-jammy"

agents:
  queue: default-queue

steps:
  - label: ":rocket: :github: MCP Release"
    command: ".buildkite/release.sh release --clean"
    artifact_paths:
      - dist/**/*
    env:
      AWS_REGION: us-east-1
    plugins:
      - aws-assume-role-with-web-identity:
          role-arn: arn:aws:iam::445615400570:role/pipeline-buildkite-buildkite-mcp-server-release
          session-tags:
            - organization_id
            - organization_slug
            - pipeline_slug
      - aws-ssm#v1.1.0:
          parameters:
            GITHUB_USER: /pipelines/buildkite/buildkite-mcp-server-release/github-user
            GITHUB_TOKEN: /pipelines/buildkite/buildkite-mcp-server-release/github-token
            DOCKERHUB_PASSWORD: /pipelines/buildkite/buildkite-mcp-server-release/dockerhub-password
            DOCKERHUB_USER: /pipelines/buildkite/buildkite-mcp-server-release/dockerhub-user
      - mise#v1.1.5: ~
