#!/usr/bin/env bash

set -euo pipefail

# Build an image for the toolchain and load it into the local image store.
if [ "${BUILDKITE_STEP_KEY:-}" == "agent" ]; then
    docker build \
	-f evals/Dockerfile \
        --load \
        --build-arg GITHUB_CLI_VERSION="${GITHUB_CLI_VERSION}" \
        --platform linux/amd64 \
        -t buildkite-mcp-server-evals:latest .
fi
